
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class GroveTownhallAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new GroveTownhallAddonDeed();
			}
		}

		[ Constructable ]
		public GroveTownhallAddon()
		{



			AddComplexComponent( (BaseAddon) this, 1801, -3, -4, 5, 1910, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 1801, -3, -2, 5, 1910, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 1801, -4, -4, 5, 1910, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 1801, -4, -3, 5, 1910, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 1801, -4, -2, 5, 1910, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 2866, -3, -3, 5, 1910, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 3025, -5, 6, 0, 0, -1, "Town Hall", 1);// 7
			AddComplexComponent( (BaseAddon) this, 1801, -2, -4, 5, 1910, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 1801, -2, -3, 5, 1910, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 1801, -2, -2, 5, 1910, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 5609, 6, -6, 0, 0, -1, "Region Controller", 1);// 11

		}

		public GroveTownhallAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class GroveTownhallAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new GroveTownhallAddon();
			}
		}

		[Constructable]
		public GroveTownhallAddonDeed()
		{
			Name = "GroveTownhall";
		}

		public GroveTownhallAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}